# Generated by Django 5.0.2 on 2025-01-20 03:16

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("nid", models.CharField(max_length=20)),
                ("p_image", models.ImageField(null=True, upload_to="image/")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_groups",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("image", models.ImageField(null=True, upload_to="image/")),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CareType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "division",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "G_username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("G_name", models.CharField(max_length=255)),
                ("CreatedDate", models.DateField(default=django.utils.timezone.now)),
                ("Topic", models.CharField(max_length=255)),
                ("Privacy", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="group_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("h_id", models.AutoField(primary_key=True, serialize=False)),
                ("h_name", models.CharField(max_length=255)),
                ("h_location", models.CharField(max_length=255)),
                ("branch", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("med_id", models.AutoField(primary_key=True, serialize=False)),
                ("disease", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                ("med_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Walk",
            fields=[
                ("walk_id", models.AutoField(primary_key=True, serialize=False)),
                ("walk_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("propose_date", models.DateField()),
                ("walk_date", models.DateField()),
                ("end_date", models.DateField()),
                ("privacy", models.CharField(max_length=255)),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Overseer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Location", models.CharField(max_length=255)),
                ("Relation", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Overseer",
                "verbose_name_plural": "Overseers",
            },
            bases=("api.user",),
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("walk_type", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Owner",
                "verbose_name_plural": "Owners",
            },
            bases=("api.user",),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("blogid", models.AutoField(primary_key=True, serialize=False)),
                ("post_date", models.DateField()),
                ("post_time", models.TimeField()),
                ("content", models.TextField()),
                (
                    "blog_img",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("cmnt_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=500)),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 1, 20, 3, 16, 5, 787330, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "blogid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.blog"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "district",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.division"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupPost",
            fields=[
                ("GPost_id", models.AutoField(primary_key=True, serialize=False)),
                ("GPost_contents", models.TextField()),
                ("GPost_Time", models.TimeField()),
                ("GPost_date", models.DateField()),
                ("GPost_image", models.ImageField(null=True, upload_to="image/")),
                (
                    "G_username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.group"
                    ),
                ),
                (
                    "p_username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupComment",
            fields=[
                ("cmnt_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=500)),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 1, 20, 3, 16, 5, 788326, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "blogid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.grouppost"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Caregiver",
            fields=[
                ("caregiver_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=10)),
                ("phone", models.PositiveIntegerField()),
                ("experience", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.caretype"
                    ),
                ),
                (
                    "h_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hospital"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thana",
            fields=[
                (
                    "thana",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.district"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hospital",
            name="thana",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.thana"
            ),
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("image", models.ImageField(null=True, upload_to="image/")),
                ("rating", models.FloatField()),
                ("experience", models.IntegerField()),
                ("dob", models.DateField()),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.agency"
                    ),
                ),
                (
                    "thana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.thana"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GhureAshi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("image", models.ImageField(null=True, upload_to="image/")),
                ("rating", models.FloatField()),
                (
                    "thana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.thana"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("EventID", models.AutoField(primary_key=True, serialize=False)),
                ("Description", models.CharField(max_length=255)),
                ("Event_title", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("Address", models.CharField(max_length=255)),
                ("create_date", models.DateField()),
                ("Approve", models.IntegerField()),
                ("E_type", models.CharField(max_length=255)),
                ("Image", models.ImageField(null=True, upload_to="Eventimage/")),
                ("privacy", models.CharField(max_length=255)),
                (
                    "Thana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.thana"
                    ),
                ),
                (
                    "E_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agency",
            name="thana",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.thana"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="thana",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.thana"
            ),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("TripID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("Location", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("propose_date", models.DateField(default=django.utils.timezone.now)),
                ("Privacy", models.CharField(max_length=255)),
                ("guide", models.CharField(max_length=255)),
                (
                    "Thana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.thana"
                    ),
                ),
                (
                    "Creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedAlert",
            fields=[
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.owner",
                    ),
                ),
                ("morning", models.TimeField()),
                ("noon", models.TimeField()),
                ("night", models.TimeField()),
                ("interval", models.IntegerField()),
                ("alert_message", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Verified",
            fields=[
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalkMember",
            fields=[
                ("wm_id", models.AutoField(primary_key=True, serialize=False)),
                ("cancel", models.IntegerField()),
                ("accept", models.IntegerField()),
                (
                    "walk_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.walk"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="walk",
            name="w_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.owner"
            ),
        ),
        migrations.CreateModel(
            name="Upvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blogid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.blog"
                    ),
                ),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripMember",
            fields=[
                ("Tid", models.AutoField(primary_key=True, serialize=False)),
                ("cancel", models.IntegerField()),
                ("Approve", models.IntegerField()),
                (
                    "TripID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.trip"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("Reply_id", models.AutoField(primary_key=True, serialize=False)),
                ("Reply_msg", models.CharField(max_length=500)),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 1, 20, 3, 16, 5, 788326, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "cmnt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="api.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("noti_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "noti_date",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 1, 20, 3, 16, 5, 788326, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("noti_msg", models.TextField()),
                (
                    "noti_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 1, 20, 3, 16, 5, 788326, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("noti_type", models.CharField(max_length=255)),
                ("noti_status", models.CharField(max_length=255)),
                (
                    "noti_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
                (
                    "noti_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to="api.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("medication_id", models.AutoField(primary_key=True, serialize=False)),
                ("meds_start_date", models.DateField()),
                ("meds_end_date", models.DateField()),
                ("dose", models.CharField(max_length=100)),
                ("after", models.CharField(max_length=100)),
                ("night", models.IntegerField()),
                ("morning", models.IntegerField()),
                ("noon", models.IntegerField()),
                ("note", models.CharField(max_length=255)),
                ("med_name", models.CharField(max_length=255)),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="med_images/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JoinEvent",
            fields=[
                ("JoinID", models.AutoField(primary_key=True, serialize=False)),
                ("Approve", models.IntegerField()),
                ("cancel", models.IntegerField()),
                (
                    "EventID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
                (
                    "Member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joined_events",
                        to="api.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndividualPost",
            fields=[
                ("PostID", models.AutoField(primary_key=True, serialize=False)),
                ("Post_contents", models.TextField()),
                ("Post_date", models.DateField()),
                ("Image", models.ImageField(null=True, upload_to="image/")),
                ("PostTime", models.IntegerField()),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupUpvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blogid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.grouppost"
                    ),
                ),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupReply",
            fields=[
                ("Reply_id", models.AutoField(primary_key=True, serialize=False)),
                ("Reply_msg", models.CharField(max_length=500)),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 1, 20, 3, 16, 5, 789321, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "cmnt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="api.groupcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("MemberID", models.AutoField(primary_key=True, serialize=False)),
                ("JoinDate", models.DateField(default=django.utils.timezone.now)),
                ("isAdmin", models.CharField(max_length=10)),
                ("Block", models.IntegerField()),
                ("accept", models.IntegerField()),
                (
                    "G_username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.group"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="Creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.owner"
            ),
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                ("f_id", models.AutoField(primary_key=True, serialize=False)),
                ("f_created_date", models.DateField()),
                ("is_fnf", models.IntegerField()),
                ("type", models.CharField(max_length=255)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user1_friends",
                        to="api.owner",
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user2_friends",
                        to="api.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoneMed",
            fields=[
                ("done_id", models.AutoField(primary_key=True, serialize=False)),
                ("done_date", models.DateField(max_length=255)),
                ("done_time", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("msgID", models.AutoField(primary_key=True, serialize=False)),
                ("message_time", models.DateTimeField()),
                ("Msg", models.CharField(max_length=255)),
                (
                    "Receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="api.owner",
                    ),
                ),
                (
                    "Sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="api.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Additional",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.owner"
                    ),
                ),
            ],
        ),
    ]
